# Generated by Django 2.1.2 on 2018-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181006_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hps',
            field=models.ManyToManyField(to='app.HealthProvider'),
        ),
    ]
